"""
 ,-*
(_)

@author: Boris Daszuta
@SPDX-License-Identifier: BSD-3-Clause
@function: Tridiagonal and pentadiagonal linear system solvers
           (Thomas algorithm, PTRANS-I).

"""
from numpy import (empty, )

from pynalgo.common_tools import (NDArray, Any, JIT, TYPE_CHECKING)

###############################################################################
# Tridiagonal
###############################################################################

def solver_tridiagonal(a : NDArray[Any],
                       b : NDArray[Any],
                       c : NDArray[Any],
                       y : NDArray[Any]) -> NDArray[Any]:
  '''
  Solver for x in Tx=y where T is tridiagonal with structure:

    b_0     c_0      0      ...
    a_0     b_1     c_1      0      ...
     0      a_1     b_2     c_2      0      ...
     .       0       .       .       .       .
             .       0    a_{n-3} b_{n-2} c_{n-2}
                     .       0    a_{n-2} b_{n-1}
  Therefore for P = [nxn]:
    a = [n-1]
    b = [n]
    c = [n-1]

  This uses the Thomas algorithm.

  Inputs are preserved.

  Note
  ----
  No checks are performed as to whether P is invertible.
  '''
  sz = b.size

  # create scratch arrays for Thomas algorithm
  c_star = empty(sz-1, dtype=y.dtype)
  d_star = empty(sz, dtype=y.dtype)
  x = empty(sz, dtype=y.dtype)

  # Forward sweep
  c_star[0] = c[0] / b[0]
  d_star[0] = y[0] / b[0]

  for ix in range(1, sz-1):
    m = 1. / (b[ix] - a[ix-1] * c_star[ix-1])
    c_star[ix] = c[ix] * m
    d_star[ix] = (y[ix] - a[ix-1] * d_star[ix-1]) * m

  m = 1. / (b[sz-1] - a[sz-2] * c_star[sz-2])
  d_star[sz-1] = (y[sz-1] - a[sz-2] * d_star[sz-2]) * m

  # Backward sweep
  x[sz-1] = d_star[sz-1]
  for ix in range(sz-2, -1, -1):
    x[ix] = d_star[ix] - c_star[ix] * x[ix+1]
  return x

###############################################################################
# JIT if not type-checking as required
###############################################################################

if TYPE_CHECKING:
  reveal_locals()  # noqa: F821
else:
  solver_tridiagonal = JIT(solver_tridiagonal)

###############################################################################
# Pentadiagonal
###############################################################################

def solver_pentadiagonal(a : NDArray[Any],
                         b : NDArray[Any],
                         c : NDArray[Any],
                         d : NDArray[Any],
                         e : NDArray[Any],
                         y : NDArray[Any]) -> NDArray[Any]:
  r'''Solver for x in Px=y where P is pentadiagonal with structure:

    d_0     a_0     b_0      0      ...
    c_0     d_1     a_1     b_1      0      ...
    e_0     c_1     d_2     a_2     b_2      0      ...
     0      e_1     c_2     d_3     a_3     b_3      0     ...
     .       0       .       .       .       .       .      .
             .       0    e_{n-5} c_{n-4} d_{n-3} a_{n-3} b_{n-3}
                     .       0    e_{n-4} c_{n-3} d_{n-2} a_{n-2}
                                     0    e_{n-3} c_{n-2} d_{n-1}

  Therefore for P = [nxn]:
    a = [n-1]
    b = [n-2]
    c = [n-1]
    d = [n]
    e = [n-2]

  Algorithm is PTRANS-I.

  Inputs are preserved.

  Note
  ----
  No checks are performed as to whether P is invertible.

  Reference
  ---------
    S. S. Askar and A. A. Karawia
    'On Solving Pentadiagonal Linear Systems via Transformations',
    Research Article, Mathematical Problems in Engineering
    (Hindawi, 31 March 2015), https://doi.org/10.1155/2015/232456.
  '''
  return _solver_pentadiagonal_1d(a, b, c, d, e, y)

def solver_pentadiagonalF(a : NDArray[Any],
                          b : NDArray[Any],
                          c : NDArray[Any],
                          d : NDArray[Any],
                          e : NDArray[Any]):
  '''
  Utility for precomputation of pentadiagonal solver factors.

  Returns
  -------
  (al, be, ga_mu, e_mu, i_mu)

  See also
  --------
    solver_pentadiagonal
    solver_pentadiagonalFS
  '''
  return _solver_pentadiagonalF_1d(a, b, c, d, e)

def solver_pentadiagonalFS(al : NDArray[Any],
                           be : NDArray[Any],
                           ga_mu : NDArray[Any],
                           e_mu : NDArray[Any],
                           i_mu : NDArray[Any],
                           y : NDArray[Any]) -> NDArray[Any]:
  '''
  Pentadiagonal solver based on precomputed factors.

  Parameters
  ----------
  (al, be, ga_mu, e_mu, i_mu): arrays generated by solver_pentadiagonalF
  y: array RHS

  See also
  --------
    solver_pentadiagonal
    solver_pentadiagonalF
  '''
  return _solver_pentadiagonalFS_1d(al, be, ga_mu, e_mu, i_mu, y)


def _solver_pentadiagonal_1d(a, b, c, d, e, y):
  sz = d.size

  al = empty(sz-1, dtype=d.dtype)
  be = empty(sz-2, dtype=d.dtype)
  ga = empty(sz-1, dtype=d.dtype)
  mu = empty(sz, dtype=d.dtype)

  z = empty(sz, dtype=d.dtype)
  x = empty(sz, dtype=d.dtype)

  # step 3
  mu[0] = d[0]
  al[0] = a[0] / mu[0]
  be[0] = b[0] / mu[0]
  z[0] = y[0] / mu[0]

  # step 4
  ga[0] = c[0]
  mu[1] = d[1] - al[0] * ga[0]
  al[1] = (a[1] - be[0] * ga[0]) / mu[1]
  be[1] = b[1] / mu[1]
  z[1] = (y[1] - z[0] * ga[0]) / mu[1]

  # step 5
  for i in range(2, sz-2):
    ga[i-1] = c[i-1] - al[i-2] * e[i-2]
    mu[i] = d[i] - be[i-2] * e[i-2] - al[i-1] * ga[i-1]
    al[i] = (a[i] - be[i-1] * ga[i-1]) / mu[i]
    be[i] = b[i] / mu[i]
    z[i] = (y[i] - z[i-2] * e[i-2] - z[i-1] * ga[i-1]) / mu[i]

  ga[sz-3] = c[sz-3] - al[sz-4] * e[sz-4]
  mu[sz-2] = d[sz-2] - be[sz-4] * e[sz-4] - al[sz-3] * ga[sz-3]
  al[sz-2] = (a[sz-2] - be[sz-3] * ga[sz-3]) / mu[sz-2]

  ga[sz-2] = c[sz-2] - al[sz-3] * e[sz-3]
  mu[sz-1] = d[sz-1] - be[sz-3] * e[sz-3] - al[sz-2] * ga[sz-2]

  z[sz-2] = (y[sz-2] - z[sz-4] * e[sz-4] - z[sz-3] * ga[sz-3]) / mu[sz-2]
  z[sz-1] = (y[sz-1] - z[sz-3] * e[sz-3] - z[sz-2] * ga[sz-2]) / mu[sz-1]

  # step 6
  x[sz-1] = z[sz-1]
  x[sz-2] = z[sz-2] - al[sz-2] * x[sz-1]

  for i in range(sz-3, -1, -1):
    x[i] = z[i] - al[i] * x[i+1] - be[i] * x[i+2]

  return x


def _solver_pentadiagonalF_1d(a, b, c, d, e):
  sz = d.size

  al = empty(sz-1, dtype=d.dtype)
  be = empty(sz-2, dtype=d.dtype)
  ga = empty(sz-1, dtype=d.dtype)
  mu = empty(sz, dtype=d.dtype)

  # step 3
  mu[0] = d[0]
  al[0] = a[0] / mu[0]
  be[0] = b[0] / mu[0]

  # step 4
  ga[0] = c[0]
  mu[1] = d[1] - al[0] * ga[0]
  al[1] = (a[1] - be[0] * ga[0]) / mu[1]
  be[1] = b[1] / mu[1]

  # step 5
  for i in range(2, sz-2):
    ga[i-1] = c[i-1] - al[i-2] * e[i-2]
    mu[i] = d[i] - be[i-2] * e[i-2] - al[i-1] * ga[i-1]
    al[i] = (a[i] - be[i-1] * ga[i-1]) / mu[i]
    be[i] = b[i] / mu[i]

  ga[sz-3] = c[sz-3] - al[sz-4] * e[sz-4]
  mu[sz-2] = d[sz-2] - be[sz-4] * e[sz-4] - al[sz-3] * ga[sz-3]
  al[sz-2] = (a[sz-2] - be[sz-3] * ga[sz-3]) / mu[sz-2]

  ga[sz-2] = c[sz-2] - al[sz-3] * e[sz-3]
  mu[sz-1] = d[sz-1] - be[sz-3] * e[sz-3] - al[sz-2] * ga[sz-2]

  ga_mu = ga / mu[1:]
  e_mu = e / mu[2:]
  _mu = 1 / mu
  return al, be, ga_mu, e_mu, _mu


def _solver_pentadiagonalFS_1d(al, be, ga_mu, e_mu, i_mu, y):
  sz = i_mu.size

  z = empty(sz, dtype=y.dtype)
  x = empty(sz, dtype=y.dtype)

  # step 3
  z[0] = y[0] * i_mu[0]

  # step 4
  z[1] = y[1] * i_mu[1] - z[0] * ga_mu[0]

  # step 5
  for i in range(2, sz-2):
    z[i] = y[i] * i_mu[i] - z[i-2] * e_mu[i-2] - z[i-1] * ga_mu[i-1]

  z[sz-2] = (y[sz-2] * i_mu[sz-2]
             -z[sz-4] * e_mu[sz-4]
             -z[sz-3] * ga_mu[sz-3])
  z[sz-1] = (y[sz-1] * i_mu[sz-1]
             -z[sz-3] * e_mu[sz-3]
             -z[sz-2] * ga_mu[sz-2])

  # step 6
  x[sz-1] = z[sz-1]
  x[sz-2] = z[sz-2] - al[sz-2] * x[sz-1]

  for i in range(sz-3, -1, -1):
    x[i] = z[i] - al[i] * x[i+1] - be[i] * x[i+2]

  return x

###############################################################################
# JIT if not type-checking as required
###############################################################################

if TYPE_CHECKING:
  reveal_locals()  # noqa: F821
else:
  _solver_pentadiagonal_1d = JIT(_solver_pentadiagonal_1d)
  _solver_pentadiagonalF_1d = JIT(_solver_pentadiagonalF_1d)
  _solver_pentadiagonalFS_1d = JIT(_solver_pentadiagonalFS_1d)

#
# :D
#
